// src/pages/Home.jsx
import React from 'react';
import { ShieldCheck, Zap, Layers, Sliders, Lock, LineChart, FileText } from 'lucide-react';

export default function Home({ setActiveTab }) {
  return (
    <div className="flex flex-col gap-5">
      <div className="bg-blue-500/8 border border-blue-500/25 rounded-2xl p-4.5">
        <h3 className="text-base font-semibold text-white flex items-center gap-2 mb-2">
          <ShieldCheck size={18} className="text-blue-400" />
          Multi-Layer Voice Authentication Strategy
        </h3>
        <p className="text-xs text-zinc-300 leading-relaxed">
          VoiceGuard protects financial institutions, bank customer support lines, wire transfer approvals, and credential resets from synthetic voice clones generated by ElevenLabs, VALL-E, and neural speech models using client-side signal analysis and out-of-band telephony callbacks.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div className="bg-white/3 border border-white/8 rounded-xl p-4.5 hover:border-white/20 transition-all">
          <div className="w-9 h-9 rounded-lg bg-white/6 border border-white/10 text-white grid place-items-center mb-3">
            <Zap size={18} />
          </div>
          <h4 className="text-sm font-semibold text-white mb-1.5">Client-Side PCM Feature Extraction</h4>
          <p className="text-xs text-zinc-400 leading-relaxed">
            Processes raw PCM audio in linear time using Web Audio API: computing RMS Energy Variance, Zero Crossing Rate, First-Difference High-Pass Energy, Pitch Periodicity, Silence Ratio, and Dynamic Range.
          </p>
        </div>

        <div className="bg-white/3 border border-white/8 rounded-xl p-4.5 hover:border-white/20 transition-all">
          <div className="w-9 h-9 rounded-lg bg-white/6 border border-white/10 text-white grid place-items-center mb-3">
            <Layers size={18} />
          </div>
          <h4 className="text-sm font-semibold text-white mb-1.5">Dual-Layer Detection Strategy</h4>
          <p className="text-xs text-zinc-400 leading-relaxed">
            Pairs AI acoustic scoring (RawNet2, Spectrogram CNN, VocoderID) with Non-AI Out-of-Band telephony verification (Unified Callback &amp; OTP token validation).
          </p>
        </div>

        <div className="bg-white/3 border border-white/8 rounded-xl p-4.5 hover:border-white/20 transition-all">
          <div className="w-9 h-9 rounded-lg bg-white/6 border border-white/10 text-white grid place-items-center mb-3">
            <Sliders size={18} />
          </div>
          <h4 className="text-sm font-semibold text-white mb-1.5">Sensitivity-Based Risk Fusion</h4>
          <p className="text-xs text-zinc-400 leading-relaxed">
            Dynamically adjusts risk authorization thresholds based on request criticality (e.g. $50,000 wire transfer vs. account balance inquiry).
          </p>
        </div>

        <div className="bg-white/3 border border-white/8 rounded-xl p-4.5 hover:border-white/20 transition-all">
          <div className="w-9 h-9 rounded-lg bg-white/6 border border-white/10 text-white grid place-items-center mb-3">
            <Lock size={18} />
          </div>
          <h4 className="text-sm font-semibold text-white mb-1.5">Short-Clip &amp; Privacy Protection</h4>
          <p className="text-xs text-zinc-400 leading-relaxed">
            Clips under 2.0 seconds are capped at 0.48 confidence to prevent false positive blocks; raw audio is processed ephemerally in RAM without persistent voice storage.
          </p>
        </div>
      </div>

      <div className="flex gap-3 mt-2">
        <button
          onClick={() => setActiveTab('live')}
          className="px-5 py-3 rounded-xl text-xs font-semibold bg-white text-black hover:bg-zinc-200 transition-all flex items-center gap-2 cursor-pointer"
        >
          <LineChart size={14} /> Launch Interactive Playground
        </button>
        <button
          onClick={() => setActiveTab('dashboard')}
          className="px-5 py-3 rounded-xl text-xs font-semibold bg-[#27272a] text-white border border-white/15 hover:bg-[#3f3f46] transition-all flex items-center gap-2 cursor-pointer"
        >
          <FileText size={14} /> Executive System Dashboard
        </button>
      </div>
    </div>
  );
}
